version: 0.2
phases:
  pre_build:
    commands:
      - PASSWORD="$(aws ecr get-login-password --region ${AWS_REGION})"
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:latest"
      - LOGIN="193733620535.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - NODE_ENV="NODE_ENV=${NODE_ENV}"
  build:
    commands:
      - docker login --username AWS --password "$PASSWORD" "$LOGIN"
      - docker build --tag "$IMAGE_URI" . --build-arg "$NODE_ENV"
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"fit-me","imageUri":"%s"}]' "$IMAGE_URI" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
