export enum ENV_VARIABLE_NAMES {
  NODE_ENV = 'NODE_ENV',
  MONGO_DB = 'MONGO_DB',
  JWT_SECRET = 'JWT_SECRET',
  MONGODB_URI = 'MONGODB_URI',
  LOCAL_MONGO_DB = 'LOCAL_MONGO_DB',
  JWT_EXPIRY_TIME = 'JWT_EXPIRY_TIME',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_ASSETS_BUCKET_NAME = 'AWS_ASSETS_BUCKET_NAME',
  AWS_ASSETS_BUCKET_REGION = 'AWS_ASSETS_BUCKET_REGION',
}
