export enum ENV_VARIABLE_NAMES {
  LOCAL_MONGO_DB = 'LOCAL_MONGO_DB',
  NODE_ENV = 'NODE_ENV',
  MONGO_DB = 'MONGO_DB',
  JWT_SECRET = 'JWT_SECRET',
  MONGODB_URI = 'MONGODB_URI',
  JWT_EXPIRY_TIME = 'JWT_EXPIRY_TIME',
}
