export enum PLAN_TYPE {
  DIET = 'DIET',
  WORKOUT = 'WORKOUT',
  DIET_AND_WORKOUT = 'DIET_AND_WORKOUT',
}

export enum FOLLOW_UP_FREQUENCY {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BI_WEEKLY = 'BI_WEEKLY',
  TRI_WEEKLY = 'TRI_WEEKLY',
  EVERY_FOUR_WEEKS = 'EVERY_FOUR_WEEKS',
  NEVER = 'NEVER',
}
